version: '3.8'

services:
  # Serviço 1: Frontend (serve) + Proxy HLS (node)
  frontend:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000" # Site acessível na porta 3000
      - "4001:4001" # Proxy acessível na porta 4001
    environment:
      - NODE_ENV=production
    depends_on:
      - api-aniwatch

  # Serviço 2: API Aniwatch (HiAnime)
  api-aniwatch:
    build: ./aniwatch-api
    restart: unless-stopped
    ports:
      - "4000:4000" # API acessível na porta 4000
    environment:
      - PORT=4000
      - ANIWATCH_API_CORS_ALLOWED_ORIGINS=*
